### ISSUE TITLE
Root sprouts have confidence field in observation page

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/Treesnap-mobile#479] opened 2018-07-12 20:42 UTC
self explanatory.

Note:  the label was created to trakc which issues are Torreya so i can easily respond to user.

**Comment by bradfordcondon** [comment] 2018-07-15 17:15
really?  But the DCP defines if it *should* have a confidence question.  And the confidence is scored in the metadata: wouldnt either checking for a confidence key in the metadata, or checking the DCP, resolve this?

**Comment by almasaeed2010** [comment] 2018-07-15 17:43
Yeah if we can check before setting the meta data we can fix this. The issue is with what’s already in the realm DB so we are gonna also need a migration to remove the confidence from fields that don’t need it

**Comment by almasaeed2010** [comment] 2018-07-16 20:04
Fixed in #507

**Closed by almasaeed2010** 2018-07-16 20:04 UTC
Labels: torreya
